"""
VaidyaMD HMS — Analytics & Clinical/Financial Reporting Router
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func, desc
from datetime import date, datetime, timedelta
from typing import Optional

from app.core.database import get_db
from app.core.models import Invoice, Patient, TreatmentCycle, TreatmentCycleStatus, User, Hospital

router = APIRouter(prefix="/analytics", tags=["Analytics & Reports"])


@router.get("/financial/income-by-user")
async def income_by_user(db: AsyncSession = Depends(get_db)):
    """Calculate collections/income attributed by user/consultant."""
    query = (
        select(
            User.name.label("user_name"),
            User.role.label("user_role"),
            func.count(Invoice.id).label("total_invoices"),
            func.sum(Invoice.paid_amount).label("total_collected"),
            func.sum(Invoice.total_amount - Invoice.paid_amount).label("total_due"),
        )
        .join(Invoice, Invoice.created_by == User.id)
        .group_by(User.id, User.name, User.role)
        .order_by(desc("total_collected"))
    )
    result = await db.execute(query)
    rows = result.all()
    return [
        {
            "user_name": r.user_name,
            "role": str(r.user_role.value if hasattr(r.user_role, "value") else r.user_role),
            "invoices_count": r.total_invoices or 0,
            "total_collected": float(r.total_collected or 0),
            "total_due": float(r.total_due or 0),
        }
        for r in rows
    ]


@router.get("/financial/income-by-referral")
async def income_by_referral(db: AsyncSession = Depends(get_db)):
    """Calculate revenue generated by referral source / doctor / marketing."""
    query = (
        select(
            func.coalesce(Patient.referred_by_name, "Self / Walk-in").label("referral_name"),
            func.coalesce(Patient.referred_by_type, "walk_in").label("referral_type"),
            func.count(Invoice.id).label("total_invoices"),
            func.sum(Invoice.total_amount).label("total_billed"),
            func.sum(Invoice.paid_amount).label("total_collected"),
        )
        .join(Invoice, Invoice.patient_id == Patient.id)
        .group_by(Patient.referred_by_name, Patient.referred_by_type)
        .order_by(desc("total_collected"))
    )
    result = await db.execute(query)
    rows = result.all()
    return [
        {
            "referral_name": r.referral_name,
            "referral_type": r.referral_type,
            "invoices_count": r.total_invoices or 0,
            "total_billed": float(r.total_billed or 0),
            "total_collected": float(r.total_collected or 0),
        }
        for r in rows
    ]


@router.get("/financial/income-by-service")
async def income_by_service(db: AsyncSession = Depends(get_db)):
    """Breakdown collections by department / appointment source."""
    query = (
        select(
            func.coalesce(Invoice.appointment_source, "OP").label("department"),
            func.count(Invoice.id).label("invoice_count"),
            func.sum(Invoice.total_amount).label("total_billed"),
            func.sum(Invoice.paid_amount).label("total_collected"),
        )
        .group_by(Invoice.appointment_source)
        .order_by(desc("total_collected"))
    )
    result = await db.execute(query)
    rows = result.all()
    return [
        {
            "department": r.department,
            "invoice_count": r.invoice_count or 0,
            "total_billed": float(r.total_billed or 0),
            "total_collected": float(r.total_collected or 0),
        }
        for r in rows
    ]


@router.get("/patients/by-city")
async def patients_by_city(db: AsyncSession = Depends(get_db)):
    """Patient registration distribution by geographical area / city."""
    query = (
        select(
            func.coalesce(Patient.area, "City Centre").label("area"),
            func.count(Patient.id).label("patient_count"),
        )
        .group_by(Patient.area)
        .order_by(desc("patient_count"))
    )
    result = await db.execute(query)
    rows = result.all()
    return [{"area": r.area, "patient_count": r.patient_count} for r in rows]


@router.get("/clinical/cycle-outcomes")
async def cycle_outcomes(db: AsyncSession = Depends(get_db)):
    """Clinical IVF / ART Cycle outcome metrics."""
    result = await db.execute(select(TreatmentCycle))
    cycles = result.scalars().all()

    total_cycles = len(cycles)
    completed = sum(1 for c in cycles if c.status == TreatmentCycleStatus.COMPLETED)
    running = sum(1 for c in cycles if c.status == TreatmentCycleStatus.RUNNING)
    cancelled = sum(1 for c in cycles if c.status == TreatmentCycleStatus.CANCELLED)

    by_type = {}
    for c in cycles:
        by_type[c.treatment_type] = by_type.get(c.treatment_type, 0) + 1

    cancellation_reasons = {}
    for c in cycles:
        if c.cancellation_reason:
            cancellation_reasons[c.cancellation_reason] = cancellation_reasons.get(c.cancellation_reason, 0) + 1

    return {
        "summary": {
            "total_cycles": total_cycles,
            "running": running,
            "completed": completed,
            "cancelled": cancelled,
            "completion_rate_pct": round((completed / total_cycles * 100), 1) if total_cycles > 0 else 0,
        },
        "by_treatment_type": by_type,
        "cancellation_reasons": cancellation_reasons,
    }
